In [38]:
import pandas as pd
import numpy as np
from numpy import genfromtxt
import csv

---
### 🟩 Monte-Carlo-Markov-Chain

Write a Customer class that represents a single customer in the supermarket.

Uses a transition probability matrix to simulate the journey of a single customer through the market. Use a Markov model to represent the state of a customer. Use one-minute time intervals for the transitions.

Once a customer reaches the checkout, consider them churned – do not simulate them any longer.

As attributes, the class should take in an id, a transition probability matrix (which you extracted earlier from the Data Analysis section) and an initial state.

---

In [7]:
matrix_monday = pd.read_csv('../data/mm_monday.csv', index_col = 0).T
matrix_monday

after   checkout     dairy    drinks     fruit    spices
dairy   0.088800  0.744772  0.062446  0.051561  0.052421
drinks  0.208109  0.011236  0.610650  0.090865  0.079140
entry   0.000000  0.284727  0.160332  0.359364  0.195577
fruit   0.205168  0.088097  0.050901  0.608066  0.047768
spices  0.144372  0.191680  0.176998  0.097064  0.389886

In [34]:
matrix_monday = np.array(matrix_monday)
matrix_monday

array([[0.08879977, 0.74477227, 0.06244629, 0.05156116, 0.05242051],
       [0.20810943, 0.01123596, 0.61064973, 0.09086468, 0.07914021],
       [0.        , 0.28472702, 0.16033172, 0.3593642 , 0.19557706],
       [0.20516836, 0.0880971 , 0.05090055, 0.60806578, 0.04776821],
       [0.14437194, 0.19168026, 0.17699837, 0.09706362, 0.38988581]])

In [35]:
class Customer:

   def __init__(self, id, state, transition_mat):
      self.id = id
      self.state = state
      self.transition_mat = transition_mat

   def __repr__(self):
      """
      Returns a csv string for that customer.
      """
      return f'{self.id};{self.state}'

   def is_active(self):
      """
      Returns True if the customer has not reached the checkout
      for the second time yet, False otherwise.
      """
      if self.state == 'checkout':
         return True 
      if self.state != 'checkout':
         return False 

   def next_state(self):
      """
      Propagates the customer to the next state
      using a weighted random choice from the transition probabilities
      conditional on the current state.
      Returns nothing.
      """
      # Below are just dummy probas for testing purposes
      #self.state = np.random.choice(['Spices', 'Drinks', 'Fruits', 'Dairy', 'Checkout'], p=[0.2, 0.2, 0.1, 0.2, 0.3])

      dairy_array = self.transition_mat[0,:]
      drinks_array = self.transition_mat[1,:]
      entry_array = self.transition_mat[2,:]
      fruit_array = self.transition_mat[3,:]
      spices_array = self.transition_mat[4,:]

      if self.state == 'dairy':
         self.state = np.random.choice(['checkout', 'dairy', 'drinks', 'fruit', 'spices'], p=dairy_array)
      if self.state == 'drinks':
         self.state = np.random.choice(['checkout', 'dairy', 'drinks', 'fruit', 'spices'], p=drinks_array)
      if self.state == 'entry':
         self.state = np.random.choice(['checkout', 'dairy', 'drinks', 'fruit', 'spices'], p=entry_array)
      if self.state == 'fruit':
         self.state = np.random.choice(['checkout', 'dairy', 'drinks', 'fruit', 'spices'], p=fruit_array)
      if self.state == 'spices':
         self.state = np.random.choice(['checkout', 'dairy', 'drinks', 'fruit', 'spices'], p=spices_array)

In [26]:
matrix_monday

array([[0.08879977, 0.74477227, 0.06244629, 0.05156116, 0.05242051],
       [0.20810943, 0.01123596, 0.61064973, 0.09086468, 0.07914021],
       [0.        , 0.28472702, 0.16033172, 0.3593642 , 0.19557706],
       [0.20516836, 0.0880971 , 0.05090055, 0.60806578, 0.04776821],
       [0.14437194, 0.19168026, 0.17699837, 0.09706362, 0.38988581]])

In [27]:
matrix_monday.shape

(5, 5)

In [28]:
matrix_monday[1,:]

array([0.20810943, 0.01123596, 0.61064973, 0.09086468, 0.07914021])

In [29]:
c9999 = Customer(9999, 'spices', matrix_monday)
c9999.next_state()
c9999

9999;spices

In [33]:
for c in range (1,21):
    customer = Customer(c, 'spices', matrix_monday)
    customer.next_state()
    print(customer)

1;spices
2;spices
3;dairy
4;fruit
5;drinks
6;dairy
7;checkout
8;drinks
9;spices
10;spices
11;spices
12;drinks
13;drinks
14;checkout
15;spices
16;spices
17;drinks
18;checkout
19;spices
20;fruit
